// generated from rosidl_generator_dotnet/resource/idl.h.em
// with input from sensor_msgs:msg\Range.idl
// generated code does not contain a copyright notice
#ifndef RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_H
#define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_H

#if defined(WIN32)
    //  Microsoft
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT __declspec(dllexport)
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_IMPORT __declspec(dllimport)
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_CDECL __cdecl
#elif defined(__GNUC__)
    //  GCC
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT __attribute__((visibility("default")))
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_IMPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_CDECL __attribute__((__cdecl__))
#else
    //  do nothing and hope for the best?
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_IMPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_CDECL
    #pragma warning Unknown dynamic link import/export semantics.
#endif

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_CDECL sensor_msgs__msg__Range__create_native_message();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
const void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_CDECL sensor_msgs__msg__Range__get_typesupport();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_CDECL sensor_msgs__msg__Range__create_native_message();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
void RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_CDECL sensor_msgs__msg__Range__destroy_native_message(void *);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_CDECL sensor_msgs__msg__Range__get_field_header_HANDLE(void *);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
uint8_t RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_CDECL sensor_msgs__msg__Range__read_field_radiation_type(void *);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
void sensor_msgs__msg__Range__write_field_radiation_type(void *, uint8_t);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
float RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_CDECL sensor_msgs__msg__Range__read_field_field_of_view(void *);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
void sensor_msgs__msg__Range__write_field_field_of_view(void *, float);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
float RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_CDECL sensor_msgs__msg__Range__read_field_min_range(void *);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
void sensor_msgs__msg__Range__write_field_min_range(void *, float);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
float RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_CDECL sensor_msgs__msg__Range__read_field_max_range(void *);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
void sensor_msgs__msg__Range__write_field_max_range(void *, float);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
float RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_CDECL sensor_msgs__msg__Range__read_field_range(void *);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
void sensor_msgs__msg__Range__write_field_range(void *, float);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_EXPORT
void RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_CDECL sensor_msgs__msg__Range__destroy_native_message(void * raw_ros_message);

#endif // RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_RANGE_H
