// generated from rosidl_generator_dotnet/resource/idl.h.em
// with input from sensor_msgs:msg\JointState.idl
// generated code does not contain a copyright notice
#ifndef RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_H
#define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_H

#if defined(WIN32)
    //  Microsoft
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT __declspec(dllexport)
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_IMPORT __declspec(dllimport)
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL __cdecl
#elif defined(__GNUC__)
    //  GCC
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT __attribute__((visibility("default")))
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_IMPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL __attribute__((__cdecl__))
#else
    //  do nothing and hope for the best?
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_IMPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL
    #pragma warning Unknown dynamic link import/export semantics.
#endif

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__create_native_message();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
const void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__get_typesupport();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__create_native_message();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
void RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__destroy_native_message(void *);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__get_field_header_HANDLE(void *);
// TODO: sequences of this type not yet supported
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__get_field_position_message(void *, int);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
int RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__getsize_sequence_field_position_message();
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
int RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__resize_sequence_field_position_message(void *, int);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
void sensor_msgs__msg__JointState__write_field_position(void *, double);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
double RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__read_field_position(void *);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__get_field_velocity_message(void *, int);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
int RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__getsize_sequence_field_velocity_message();
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
int RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__resize_sequence_field_velocity_message(void *, int);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
void sensor_msgs__msg__JointState__write_field_velocity(void *, double);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
double RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__read_field_velocity(void *);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__get_field_effort_message(void *, int);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
int RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__getsize_sequence_field_effort_message();
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
int RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__resize_sequence_field_effort_message(void *, int);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
void sensor_msgs__msg__JointState__write_field_effort(void *, double);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
double RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__read_field_effort(void *);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_EXPORT
void RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_CDECL sensor_msgs__msg__JointState__destroy_native_message(void * raw_ros_message);

#endif // RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_JOINTSTATE_H
