// generated from rosidl_generator_dotnet/resource/idl.h.em
// with input from sensor_msgs:msg\PointCloud.idl
// generated code does not contain a copyright notice
#ifndef RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_H
#define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_H

#if defined(WIN32)
    //  Microsoft
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT __declspec(dllexport)
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_IMPORT __declspec(dllimport)
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL __cdecl
#elif defined(__GNUC__)
    //  GCC
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT __attribute__((visibility("default")))
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_IMPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL __attribute__((__cdecl__))
#else
    //  do nothing and hope for the best?
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_IMPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL
    #pragma warning Unknown dynamic link import/export semantics.
#endif

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL sensor_msgs__msg__PointCloud__create_native_message();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT
const void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL sensor_msgs__msg__PointCloud__get_typesupport();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL sensor_msgs__msg__PointCloud__create_native_message();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT
void RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL sensor_msgs__msg__PointCloud__destroy_native_message(void *);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL sensor_msgs__msg__PointCloud__get_field_header_HANDLE(void *);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL sensor_msgs__msg__PointCloud__get_field_points_message(void *, int);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT
int RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL sensor_msgs__msg__PointCloud__getsize_sequence_field_points_message();
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT
int RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL sensor_msgs__msg__PointCloud__resize_sequence_field_points_message(void *, int);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL sensor_msgs__msg__PointCloud__get_field_channels_message(void *, int);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT
int RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL sensor_msgs__msg__PointCloud__getsize_sequence_field_channels_message();
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT
int RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL sensor_msgs__msg__PointCloud__resize_sequence_field_channels_message(void *, int);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_EXPORT
void RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_CDECL sensor_msgs__msg__PointCloud__destroy_native_message(void * raw_ros_message);

#endif // RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_POINTCLOUD_H
