// generated from rosidl_generator_dotnet/resource/idl.h.em
// with input from sensor_msgs:msg\MagneticField.idl
// generated code does not contain a copyright notice
#ifndef RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_H
#define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_H

#if defined(WIN32)
    //  Microsoft
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_EXPORT __declspec(dllexport)
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_IMPORT __declspec(dllimport)
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_CDECL __cdecl
#elif defined(__GNUC__)
    //  GCC
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_EXPORT __attribute__((visibility("default")))
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_IMPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_CDECL __attribute__((__cdecl__))
#else
    //  do nothing and hope for the best?
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_EXPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_IMPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_CDECL
    #pragma warning Unknown dynamic link import/export semantics.
#endif

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_CDECL sensor_msgs__msg__MagneticField__create_native_message();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_EXPORT
const void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_CDECL sensor_msgs__msg__MagneticField__get_typesupport();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_CDECL sensor_msgs__msg__MagneticField__create_native_message();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_EXPORT
void RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_CDECL sensor_msgs__msg__MagneticField__destroy_native_message(void *);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_CDECL sensor_msgs__msg__MagneticField__get_field_header_HANDLE(void *);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_CDECL sensor_msgs__msg__MagneticField__get_field_magnetic_field_HANDLE(void *);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_CDECL sensor_msgs__msg__MagneticField__get_field_magnetic_field_covariance_message(void *, int);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_EXPORT
int RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_CDECL sensor_msgs__msg__MagneticField__getsize_array_field_magnetic_field_covariance_message();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_EXPORT
void sensor_msgs__msg__MagneticField__write_field_magnetic_field_covariance(void *, double);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_EXPORT
double RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_CDECL sensor_msgs__msg__MagneticField__read_field_magnetic_field_covariance(void *);


RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_EXPORT
void RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_CDECL sensor_msgs__msg__MagneticField__destroy_native_message(void * raw_ros_message);

#endif // RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_MAGNETICFIELD_H
