// generated from rosidl_generator_dotnet/resource/idl.h.em
// with input from sensor_msgs:msg\Illuminance.idl
// generated code does not contain a copyright notice
#ifndef RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_H
#define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_H

#if defined(WIN32)
    //  Microsoft
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_EXPORT __declspec(dllexport)
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_IMPORT __declspec(dllimport)
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_CDECL __cdecl
#elif defined(__GNUC__)
    //  GCC
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_EXPORT __attribute__((visibility("default")))
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_IMPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_CDECL __attribute__((__cdecl__))
#else
    //  do nothing and hope for the best?
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_EXPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_IMPORT
    #define RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_CDECL
    #pragma warning Unknown dynamic link import/export semantics.
#endif

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_CDECL sensor_msgs__msg__Illuminance__create_native_message();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_EXPORT
const void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_CDECL sensor_msgs__msg__Illuminance__get_typesupport();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_CDECL sensor_msgs__msg__Illuminance__create_native_message();

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_EXPORT
void RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_CDECL sensor_msgs__msg__Illuminance__destroy_native_message(void *);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_EXPORT
void * RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_CDECL sensor_msgs__msg__Illuminance__get_field_header_HANDLE(void *);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_EXPORT
double RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_CDECL sensor_msgs__msg__Illuminance__read_field_illuminance(void *);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_EXPORT
void sensor_msgs__msg__Illuminance__write_field_illuminance(void *, double);
RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_EXPORT
double RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_CDECL sensor_msgs__msg__Illuminance__read_field_variance(void *);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_EXPORT
void sensor_msgs__msg__Illuminance__write_field_variance(void *, double);

RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_EXPORT
void RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_CDECL sensor_msgs__msg__Illuminance__destroy_native_message(void * raw_ros_message);

#endif // RCLDOTNET_SENSOR_MSGS_SENSOR_MSGS_MSG_ILLUMINANCE_H
