// generated from rosidl_generator_dotnet/resource/idl.h.em
// with input from nav_msgs:msg\OccupancyGrid.idl
// generated code does not contain a copyright notice
#ifndef RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_H
#define RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_H

#if defined(WIN32)
    //  Microsoft
    #define RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT __declspec(dllexport)
    #define RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_IMPORT __declspec(dllimport)
    #define RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_CDECL __cdecl
#elif defined(__GNUC__)
    //  GCC
    #define RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT __attribute__((visibility("default")))
    #define RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_IMPORT
    #define RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_CDECL __attribute__((__cdecl__))
#else
    //  do nothing and hope for the best?
    #define RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT
    #define RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_IMPORT
    #define RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_CDECL
    #pragma warning Unknown dynamic link import/export semantics.
#endif

RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT
void * RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_CDECL nav_msgs__msg__OccupancyGrid__create_native_message();

RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT
const void * RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_CDECL nav_msgs__msg__OccupancyGrid__get_typesupport();

RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT
void * RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_CDECL nav_msgs__msg__OccupancyGrid__create_native_message();

RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT
void RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_CDECL nav_msgs__msg__OccupancyGrid__destroy_native_message(void *);

RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT
void * RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_CDECL nav_msgs__msg__OccupancyGrid__get_field_header_HANDLE(void *);
RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT
void * RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_CDECL nav_msgs__msg__OccupancyGrid__get_field_info_HANDLE(void *);
RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT
void * RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_CDECL nav_msgs__msg__OccupancyGrid__get_field_data_message(void *, int);
RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT
int RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_CDECL nav_msgs__msg__OccupancyGrid__getsize_sequence_field_data_message();
RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT
int RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_CDECL nav_msgs__msg__OccupancyGrid__resize_sequence_field_data_message(void *, int);
RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT
void nav_msgs__msg__OccupancyGrid__write_field_data(void *, int8_t);
RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT
int8_t RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_CDECL nav_msgs__msg__OccupancyGrid__read_field_data(void *);

RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_EXPORT
void RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_CDECL nav_msgs__msg__OccupancyGrid__destroy_native_message(void * raw_ros_message);

#endif // RCLDOTNET_NAV_MSGS_NAV_MSGS_MSG_OCCUPANCYGRID_H
