// generated from rosidl_generator_dotnet/resource/idl.h.em
// with input from test_msgs:msg\Strings.idl
// generated code does not contain a copyright notice
#ifndef RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_H
#define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_H

#if defined(WIN32)
    //  Microsoft
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT __declspec(dllexport)
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_IMPORT __declspec(dllimport)
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL __cdecl
#elif defined(__GNUC__)
    //  GCC
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT __attribute__((visibility("default")))
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_IMPORT
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL __attribute__((__cdecl__))
#else
    //  do nothing and hope for the best?
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_IMPORT
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL
    #pragma warning Unknown dynamic link import/export semantics.
#endif

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__create_native_message();

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
const void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__get_typesupport();

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__create_native_message();

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__destroy_native_message(void *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
char * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__read_field_string_value(void *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void test_msgs__msg__Strings__write_field_string_value(void *, char *);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
char * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__read_field_string_value_default1(void *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void test_msgs__msg__Strings__write_field_string_value_default1(void *, char *);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
char * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__read_field_string_value_default2(void *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void test_msgs__msg__Strings__write_field_string_value_default2(void *, char *);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
char * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__read_field_string_value_default3(void *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void test_msgs__msg__Strings__write_field_string_value_default3(void *, char *);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
char * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__read_field_string_value_default4(void *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void test_msgs__msg__Strings__write_field_string_value_default4(void *, char *);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
char * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__read_field_string_value_default5(void *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void test_msgs__msg__Strings__write_field_string_value_default5(void *, char *);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
char * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__read_field_bounded_string_value(void *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void test_msgs__msg__Strings__write_field_bounded_string_value(void *, char *);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
char * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__read_field_bounded_string_value_default1(void *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void test_msgs__msg__Strings__write_field_bounded_string_value_default1(void *, char *);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
char * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__read_field_bounded_string_value_default2(void *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void test_msgs__msg__Strings__write_field_bounded_string_value_default2(void *, char *);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
char * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__read_field_bounded_string_value_default3(void *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void test_msgs__msg__Strings__write_field_bounded_string_value_default3(void *, char *);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
char * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__read_field_bounded_string_value_default4(void *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void test_msgs__msg__Strings__write_field_bounded_string_value_default4(void *, char *);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
char * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__read_field_bounded_string_value_default5(void *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void test_msgs__msg__Strings__write_field_bounded_string_value_default5(void *, char *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_EXPORT
void RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_CDECL test_msgs__msg__Strings__destroy_native_message(void * raw_ros_message);

#endif // RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_STRINGS_H
