// generated from rosidl_generator_dotnet/resource/idl.h.em
// with input from test_msgs:msg\MultiNested.idl
// generated code does not contain a copyright notice
#ifndef RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_H
#define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_H

#if defined(WIN32)
    //  Microsoft
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT __declspec(dllexport)
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_IMPORT __declspec(dllimport)
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL __cdecl
#elif defined(__GNUC__)
    //  GCC
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT __attribute__((visibility("default")))
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_IMPORT
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL __attribute__((__cdecl__))
#else
    //  do nothing and hope for the best?
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_IMPORT
    #define RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL
    #pragma warning Unknown dynamic link import/export semantics.
#endif

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__create_native_message();

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
const void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__get_typesupport();

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__create_native_message();

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
void RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__destroy_native_message(void *);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__get_field_array_of_arrays_message(void *, int);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__getsize_array_field_array_of_arrays_message();


RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__get_field_array_of_bounded_sequences_message(void *, int);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__getsize_array_field_array_of_bounded_sequences_message();


RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__get_field_array_of_unbounded_sequences_message(void *, int);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__getsize_array_field_array_of_unbounded_sequences_message();


RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__get_field_bounded_sequence_of_arrays_message(void *, int);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__getsize_sequence_field_bounded_sequence_of_arrays_message();
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__resize_sequence_field_bounded_sequence_of_arrays_message(void *, int);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__get_field_bounded_sequence_of_bounded_sequences_message(void *, int);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__getsize_sequence_field_bounded_sequence_of_bounded_sequences_message();
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__resize_sequence_field_bounded_sequence_of_bounded_sequences_message(void *, int);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__get_field_bounded_sequence_of_unbounded_sequences_message(void *, int);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__getsize_sequence_field_bounded_sequence_of_unbounded_sequences_message();
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__resize_sequence_field_bounded_sequence_of_unbounded_sequences_message(void *, int);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__get_field_unbounded_sequence_of_arrays_message(void *, int);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__getsize_sequence_field_unbounded_sequence_of_arrays_message();
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__resize_sequence_field_unbounded_sequence_of_arrays_message(void *, int);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__get_field_unbounded_sequence_of_bounded_sequences_message(void *, int);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__getsize_sequence_field_unbounded_sequence_of_bounded_sequences_message();
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__resize_sequence_field_unbounded_sequence_of_bounded_sequences_message(void *, int);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
void * RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__get_field_unbounded_sequence_of_unbounded_sequences_message(void *, int);
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__getsize_sequence_field_unbounded_sequence_of_unbounded_sequences_message();
RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
int RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__resize_sequence_field_unbounded_sequence_of_unbounded_sequences_message(void *, int);

RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_EXPORT
void RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_CDECL test_msgs__msg__MultiNested__destroy_native_message(void * raw_ros_message);

#endif // RCLDOTNET_TEST_MSGS_TEST_MSGS_MSG_MULTINESTED_H
