//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mediator
{
    [Serializable]
    public class GetStateServedRequest : Message
    {
        public const string k_RosMessageName = "mediator/GetStateServed";
        public override string RosMessageName => k_RosMessageName;


        public GetStateServedRequest()
        {
        }
        public static GetStateServedRequest Deserialize(MessageDeserializer deserializer) => new GetStateServedRequest(deserializer);

        private GetStateServedRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetStateServedRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
