//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mediator
{
    [Serializable]
    public class GetStateServedResponse : Message
    {
        public const string k_RosMessageName = "mediator/GetStateServed";
        public override string RosMessageName => k_RosMessageName;

        public M545.M545StateMsg state;

        public GetStateServedResponse()
        {
            this.state = new M545.M545StateMsg();
        }

        public GetStateServedResponse(M545.M545StateMsg state)
        {
            this.state = state;
        }

        public static GetStateServedResponse Deserialize(MessageDeserializer deserializer) => new GetStateServedResponse(deserializer);

        private GetStateServedResponse(MessageDeserializer deserializer)
        {
            this.state = M545.M545StateMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "GetStateServedResponse: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
