//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Mediator
{
    [Serializable]
    public class GetScaledGridMapResponse : Message
    {
        public const string k_RosMessageName = "mediator/GetScaledGridMap";
        public override string RosMessageName => k_RosMessageName;

        //  Submap
        public GridMap.GridMapMsg map;

        public GetScaledGridMapResponse()
        {
            this.map = new GridMap.GridMapMsg();
        }

        public GetScaledGridMapResponse(GridMap.GridMapMsg map)
        {
            this.map = map;
        }

        public static GetScaledGridMapResponse Deserialize(MessageDeserializer deserializer) => new GetScaledGridMapResponse(deserializer);

        private GetScaledGridMapResponse(MessageDeserializer deserializer)
        {
            this.map = GridMap.GridMapMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.map);
        }

        public override string ToString()
        {
            return "GetScaledGridMapResponse: " +
            "\nmap: " + map.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
