// generated from rosidl_generator_dotnet/resource/idl.h.em
// with input from actionlib_msgs:msg\GoalID.idl
// generated code does not contain a copyright notice
#ifndef RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_H
#define RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_H

#if defined(WIN32)
    //  Microsoft
    #define RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_EXPORT __declspec(dllexport)
    #define RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_IMPORT __declspec(dllimport)
    #define RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_CDECL __cdecl
#elif defined(__GNUC__)
    //  GCC
    #define RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_EXPORT __attribute__((visibility("default")))
    #define RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_IMPORT
    #define RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_CDECL __attribute__((__cdecl__))
#else
    //  do nothing and hope for the best?
    #define RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_EXPORT
    #define RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_IMPORT
    #define RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_CDECL
    #pragma warning Unknown dynamic link import/export semantics.
#endif

RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_EXPORT
void * RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_CDECL actionlib_msgs__msg__GoalID__create_native_message();

RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_EXPORT
const void * RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_CDECL actionlib_msgs__msg__GoalID__get_typesupport();

RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_EXPORT
void * RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_CDECL actionlib_msgs__msg__GoalID__create_native_message();

RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_EXPORT
void RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_CDECL actionlib_msgs__msg__GoalID__destroy_native_message(void *);

RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_EXPORT
void * RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_CDECL actionlib_msgs__msg__GoalID__get_field_stamp_HANDLE(void *);
RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_EXPORT
char * RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_CDECL actionlib_msgs__msg__GoalID__read_field_id(void *);

RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_EXPORT
void actionlib_msgs__msg__GoalID__write_field_id(void *, char *);

RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_EXPORT
void RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_CDECL actionlib_msgs__msg__GoalID__destroy_native_message(void * raw_ros_message);

#endif // RCLDOTNET_ACTIONLIB_MSGS_ACTIONLIB_MSGS_MSG_GOALID_H
