// generated from rosidl_generator_dotnet/resource/idl.h.em
// with input from example_interfaces:msg\WString.idl
// generated code does not contain a copyright notice
#ifndef RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_H
#define RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_H

#if defined(WIN32)
    //  Microsoft
    #define RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_EXPORT __declspec(dllexport)
    #define RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_IMPORT __declspec(dllimport)
    #define RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_CDECL __cdecl
#elif defined(__GNUC__)
    //  GCC
    #define RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_EXPORT __attribute__((visibility("default")))
    #define RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_IMPORT
    #define RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_CDECL __attribute__((__cdecl__))
#else
    //  do nothing and hope for the best?
    #define RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_EXPORT
    #define RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_IMPORT
    #define RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_CDECL
    #pragma warning Unknown dynamic link import/export semantics.
#endif

RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_EXPORT
void * RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_CDECL example_interfaces__msg__WString__create_native_message();

RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_EXPORT
const void * RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_CDECL example_interfaces__msg__WString__get_typesupport();

RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_EXPORT
void * RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_CDECL example_interfaces__msg__WString__create_native_message();

RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_EXPORT
void RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_CDECL example_interfaces__msg__WString__destroy_native_message(void *);

// TODO: Unicode types are not supported

RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_EXPORT
void RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_CDECL example_interfaces__msg__WString__destroy_native_message(void * raw_ros_message);

#endif // RCLDOTNET_EXAMPLE_INTERFACES_EXAMPLE_INTERFACES_MSG_WSTRING_H
